openapi: 3.0.3
info:
  title: Cake API
  description: A simple API to get a random list of cakes.
  version: 1.0.0

paths:
  /cakes:
    get:
      summary: Get a list of cakes
      operationId: getCakes
      responses:
        '200':
          description: A list of cakes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cake'

components:
  schemas:
    Cake:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-faker: random.number
        baker:
          type: string
          x-faker: name.firstName
